### ISSUE TITLE
Images 404

### ISSUE THREAD

**Issue by magikid** [kupad/meme-it-so#52]
Hello,

All of the images in the `static` folder on memeit.so are returning an HTTP 404 Not Found response. For example, this URL: https://memeit.so/static/thumbnails/S01/S01E01/70278.jpg returns a 404 as seen in
[this screenshot](https://github.com/kupad/meme-it-so/files/6488133/Screenshot.2021-05-08.at.2.36.03.PM.pdf).

**Comment by kupad** [comment]
Thank you for letting me know about this! I don't know why, but the volume with all the images that had been mounted has inexplicably be unmounted, and I'm having trouble mounting it again. And I'm trying to figure it out now.

**Comment by kupad** [comment]
I still don't completely understand what was happening here, but I've got the thumbnails back.

Again, thank you for letting me know!

**Comment by magikid** [comment]
Thanks for the quick resolution! Happy to help.
